name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Try to install with the full requirements.txt first
        pip install -r requirements.txt || pip install -r requirements-ci.txt

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 1
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
        # Use SQLite for CI testing
        SQL_ENGINE: django.db.backends.sqlite3
        SQL_DATABASE: ":memory:"
      run: |
        python manage.py test