name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Try to install with the full requirements.txt first
          pip install -r requirements.txt || pip install -r requirements-ci.txt
          pip install wemake-python-styleguide

      - name: Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 1
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          # Use SQLite for CI testing
          SQL_ENGINE: django.db.backends.sqlite3
          SQL_DATABASE: ":memory:"
        run: |
          python manage.py test
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}